### PR TITLE
Update schema.py and Pipfile for graphene 2.0+. Remove Pipfile.lock

### PR DESCRIPTION
**Pull request by jwalkerdev**

### CODE REVIEW

**Comment by nderkach** [comment]
Hey!

Thanks for the PR.

I don't agree with the changes in pipfiles though. The idea is that `Pipfile` contains the list of required packages and `Pifpfile.lock` constains specific versions to make a deterministic environment, and therefore is commited to git. Check out the master project for example: https://github.com/pypa/pipenv

**Comment by jwalkerdev** [comment]
I see what you are saying.  In the pypa/pipenv repo, `Pipfile` does have some specific versions, but only where needed for the current version of the repo.  So, how about I change Pipfile to only specify the version for graphene? Graphene is a key requirement for this project, and it was the key breaker.  You ok with having `Pipfile.lock` in .gitignore? That just means that everyone who uses this repo will generate their own file.

**Comment by nderkach** [comment]
`Pipfile` is not required to contain any specific version of graphene. As a matter of fact the project doesn't require it. What do you mean, "it was a key breaker"?

As for the `Pipfile.lock` I explicitly included it in the repo to create a deterministic build as suggested by the author: https://docs.pipenv.org/basics/#general-recommendations-version-control

**Comment by jwalkerdev** [comment]
I agree that Pipfile is not required to contain any specific version. However, it can specify a version if needed for code compatibility. If you look at the Pipfile in https://github.com/pypa/pipenv, you will see they did that. There is nothing wrong with targeting a version. Since this repo targets graphene use, specifying a version in Pipfile to maintain code compatibility would not be wrong.

In this repo, an updated Pipfile.lock was committed in commit f2c440bb51d75a7a45b758856eb970dcc6dd6b3f.  That Pipfile.lock file uses graphene 2.0.1, which is not compatible with the current code.

When I clone this repo into a clean directory and run `pipenv install`, then export the AIRBNB vars, and then run 'pipenv run python server.py', I get a server error when I run the graphql query from the article. When I start with a clean clone and follow your directions exactly, I get the same server error. 

To get the current master to work, you can restore the original Pipfile.lock (which makes the code compatible with graphene 1.4.1) or do something similar to my fork and support graphene 2.0.1. You could also do that by keeping the Pipfile.lock with the graphene 2.0.1 configuration and leave the version update out of Pipfile. My fork is just one way of doing that.  The same recommendations you mentioned implies using Pipfile for targeting a specific version of a technology, such as python. If that's only for specifying the python version, I imagine Pipfile would not be needed in pipenv.  I'm just saying that the recommendations don't rule out either solution, in my opinion.
That said, if you prefer to just use the Pipfile.lock, I'm glad to remove the version from Pipfile and update the PR.

**Comment by jwalkerdev** [comment]
Either way, I'll remove Pipfile.lock from .gitignore.
Good catch on that.

**Comment by nderkach** [comment]
Ok, so to summarize, the only dependency which needs to be updated is `graphene`?

In this case I'd leave `Pipfile` as is, i.e. keeping ambiguous (`"*"`) versions for all dependencies, except `graphene`, which I'd make  `">=2.0.0"`. Then you can run `pipenv install` and update `Pipfile.lock` with the most recent versions.

**Comment by jwalkerdev** [comment]
Requested changes are made.

**Review by nderkach — APPROVED** [review]
Thanks for the PR!

**Comment by jwalkerdev** [comment]
You're welcome. Thanks for the article and the initial code base.

**Pull request merged**
